# Generated by Django 4.1.5 on 2023-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://zabas.com/wp-content/uploads/2017/01/food-placeholder.png', max_length=200)),
            ],
        ),
    ]
